### ISSUE TITLE
Fix revert replay attack vulnerability

### ISSUE THREAD

**Issue by Dentosal** [pvlsil/BitcoinVoting#6]
If you decide to change what you have voted, the information from your previous vote may be publicly available, and the reused to revert new vote.

**Comment by viderizer** [comment]
This is not a problem when using HTTPS.

**Comment by viderizer** [comment]
Implemented a 5-minute timestamp check.

**Comment by Dentosal** [comment]
Improved the timestamp check in 0faaa6d. Using 10-minute timestamp now.
